import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Son Tran Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h className="text-xl">Made by Son</h>
            <ul className="flex items-center">
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r bg-slate-800 px-4 py-2 rounded text-white">
                  Resume
                </a>
              </li>
              <li>
                <a href="#"></a>
              </li>
              <li>
                <a href="#"></a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-3">
            <h2 className="text-5xl py-2 ">Son Tran</h2>
            <h3 className="text-xl py-2">Web and Mobile Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              As an individual with a passion for technology, I bring a unique
              blend of technical savvy and creative problem solving to any
              project. I am always open to learning new things and taking on new
              challenges. Whether it's creating a responsive website or building
              a feature-packed mobile app, I approach every project with
              enthusiasm and a desire to find the most efficient and enjoyable
              solutions.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
