import Projects from "@/components/sections/Projects";
import Hero from "@/components/sections/Hero";
import AboutMe from "@/components/sections/AboutMe";
import Navbar from "@/components/utils/Navbar";
import Head from "next/head";
import Skills from "@/components/sections/Skills";
import ScrollProgressBar from "@/components/utils/ScrollProgressBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Son Tran Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" px-8 bg-neutral-900 flex justify-center">
        {/* <ScrollProgressBar /> */}
        <div className=" max-w-4xl">
          <Navbar />
          <Hero />
          <AboutMe />
          {/* <Skills /> */}
          <Projects />
        </div>
      </main>
    </>
  );
}
