import ClientProjects from "@/components/sections/ClientProjects";
import Hero from "@/components/sections/Hero";
import MyProjects from "@/components/sections/MyProjects";
import AboutMe from "@/components/sections/AboutMe";
import Navbar from "@/components/utils/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Son Tran Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" px-8 bg-neutral-900">
        <Navbar />
        <Hero />
        <AboutMe />
        <ClientProjects />
        <MyProjects />
      </main>
    </>
  );
}
